### ISSUE TITLE
Problem: There is no license

### ISSUE THREAD

**Issue by barryosull** [domain-query-language/dql-server#2]
Problem: 
There is no license for using this code. This opens us up to various problems regarding liability and collaboration.

Solution: 
Choose a license and add it to the repo.

**Comment by barryosull** [comment]
Here is a list that compares various licenses. 
[](http://choosealicense.com/licenses/)

We should review this list and choose the license that best suits the needs of the project.

Here are the needs as I see them:

- The code is open source
- Anyone can download and use the source code, be it personal or commercial
- Anyone can modify the code to suit their own needs
- If they modify the code, they are obliged to share the changes with the community
- We, the developers of the code, are not liable for anything related to use of the code

The basic gist is that people should be able to use and contribute to this project.

**Comment by lyonscf** [comment]
From my perspective, we should just stick with the MIT License until we have a specific reason to change it.

**Comment by barryosull** [comment]
Cool, let's do that then.
