### ISSUE TITLE
Problem: Arguments are never actually used

### ISSUE THREAD

**Issue by barryosull** [domain-query-language/dql-server#99]
The arguments interpreter doesn't actually do anything, it just passes context back.
This shows us that there aren't tests to actually test it's behaviour. There is a possible code smell here.

**Comment by barryosull** [comment]
Arguments are properties that have been turned into an array list of values, at least, that's how it was working. Clearly this isn't good enough. Ideally the "arguments" interpreters job is to take current context, extract values from it, then return a new context with the values set, according to the keys that the next context is expecting.

**Comment by barryosull** [comment]
So far the only place the arguments interpreter is used is at the command handler level.
In order for it to be fully useful, we'd need to do some sort of translation to the current contexts values.

**Comment by barryosull** [comment]
Properties is the concept we're looking for. We need some way of specifying the properties of an object/method. Once we've nailed that down, we can feed that into the arguments interpreter, then it can do the conversion.

**Comment by barryosull** [comment]
Let's get entities working first, then we can work on this issue, as entities are frequently created from argument lists.

**Comment by shano** [comment]
I don't understand, can you give an example?

**Comment by barryosull** [comment]
No probs, this is the code for the argument interpreter at the moment.
```php
<?php namespace Infrastructure\App\Interpreter\Arguments;

use App\Interpreter\Context;

class Interpreter implements \App\Interpreter\Interpreter
{    
    private $ast;
    
    public function __construct($ast)
    {
        $this->ast = $ast;
    }
    
    public function interpret(Context $context)
    {
        $arguments = [];
        foreach ($this->ast as $argument_ast) {
            $arguments[] = $context->get_property($argument_ast->property);
        }
        return $context;
    }
}
```

You can see here that the arguments variable is never actually used, this is a sign that's something is wrong.

**Comment by barryosull** [comment]
Issue #109 will face this soon, as the "apply" method will attempt to create an event from arguments. Once we have tests for that, we'll have a better idea of how to solve this.

**Comment by barryosull** [comment]
#109 has been completed, as it has resolved this issue. Arguments are actually used correctly now. Happy with this issue, closing it.
